### ISSUE TITLE
thesaurus-lookup

### ISSUE THREAD

**Issue by TazoDvalishvili** [freeuni-paradigms/assn-3-vector-hashset#4]
./thesaurus-lookup-ის შემდეგ Could not open thesaurus file named "/usr/class/cs107/assignments/assn-3-vector-hashset-data/thesaurus.txt" ტერმინალში ეს შეტყობინება გამოაქვს და ვერ ვტესტავ და როგორ უნდა გავასწორო?

**Comment by iarigby** [comment]
@freeuni-paradigms/section-leaders

**Comment by CSopiko** [comment]
სავარაუდოდ, ეგეთი path არ არსებობს და "ხელოვნურად" უნდა შექმნა :D მეორე დავალებაში როგორც იყო: https://github.com/freeuni-paradigms/assn-2-six-degrees/issues/3#issuecomment-705548948 ეს კომენტარი ნახე, ოღონც დავალება-2ის ნაცვლად მესამესთვის ქენი, წესით ეშველება, თუ არადა დაველოდოთ პასუხს

**Comment by TazoDvalishvili** [comment]
@skurd18 კი იგივე პრობლემა ყოფილა, მადლობა.
