### ISSUE TITLE
Output-ის შემოწმება

### ISSUE THREAD

**Issue by LukeSamkharadze** [freeuni-paradigms/assn-3-vector-hashset#6]
@iarigby სწორ output-ს დავდებ შესამოწმებლადო, სადაა აბა? 😄

**Comment by iarigby** [comment]
მადლობა რომ გამახსენე, ავტვირთე, სანამ კლასრუმზე დავპოსტავ შეგიძლია შეამოწმო?

**Comment by LukeSamkharadze** [comment]
სამწუხაროდ არ დამიწყია დავალების წერა, უბრალოდ წინასწარ მინდოდა სამუშაო environment გამემზადებინა 😄

ვთხოვ ვინმეს რომ გადაამოწმოს

**Comment by LukeSamkharadze** [comment]
@iarigby დათაგე სექ-ლიდერები, იქნებ გადაამოწმონ. მე ვერ ვთაგავ. 

მგონი ჯერ არავის უწერია ეს დავალება :დ

**Comment by LukeSamkharadze** [comment]
დაემთხვაო ერთ-ერთმა 👍

**Comment by iarigby** [comment]
Btw სწორზე მქონდა უკვე შემოწმებული, უბრალოდ რამდენად სწორად დავამატე და ავტვირთე ეგ ვიგულისხმე

**Comment by LukeSamkharadze** [comment]
აა, ეგ არც მიფიქრია მაგას რო გულისხმობდი 😀

სწორად გექნებოდა ატვირთული ცხადია. მაგაში არც კი შემპარია ეჭვი 🤓
